### ISSUE TITLE
Crash when using ceil()

### ISSUE THREAD

**Issue by AthenaIak** [zhoupc/CNMF_E#13]
Firstly, thank you for sharing this project. I noticed that after the last update the program crashes here:

https://github.com/zhoupc/CNMF_E/blob/1938ef8385ae34ca9dedf7d25f2341fe3f904aad/ca_source_extraction/endoscope/correlation_image_endoscope.m#L47

Do you maybe mean `patch_sz = [ceil(d1/x) ceil(d2/x)];` ?

**Comment by zhoupc** [comment]
@AthenaIak good catch. Thanks for reporting this nasty bug.
