### ISSUE TITLE
CVX requirement doesn't work for Matlab 2017a

### ISSUE THREAD

**Issue by outlace** [zhoupc/CNMF_E#14]
```
IMPORTANT NOTE ABOUT MATLAB R2017a or later: a number of users are reporting issues with
CVX and R2017a; and indeed, we’re seeing them too. At the moment, we must assume that MATLAB
R2017a is *not* compatible with CVX. If you need to use CVX, you will need to stick with R2016b or
earlier. We do not have a timeline for a fix yet.
```

Is there anyway around this? An alternative de-noising dependency we could use?

**Comment by zhoupc** [comment]
@outlace can you just ignore those warnings and try those demo scripts directly. Previously I mainly use cvx for spike inference as used in Eftychios implementation. Later we have OASIS algorithm that is much faster than cvx and I don't use it anymore. maybe you can try it and then tell me if other places still need CVX. Thanks.

**Comment by outlace** [comment]
You're right, it seems to be working for me now. I tried awhile ago and got an error
