### ISSUE TITLE
Typographic error in detrend data

### ISSUE THREAD

**Issue by AthenaIak** [zhoupc/CNMF_E#15]
Hello,

https://github.com/zhoupc/CNMF_E/blob/f1e08e89fff8b90354b6c4bb0d3a7dfa12f898d5/ca_source_extraction/endoscope/detrend_data.m#L22

I think you want to compare with "spline" (the "p" is missing).

edit: Found another one
https://github.com/zhoupc/CNMF_E/blob/f1e08e89fff8b90354b6c4bb0d3a7dfa12f898d5/ca_source_extraction/endoscope/greedyROI_endoscope.m#L322

ind_succwss should be ind_success .

**Comment by zhoupc** [comment]
ha, thanks for catching these nasty typos. @AthenaIak . they are fixed.
