### ISSUE TITLE
The consuct "Ysignal(...end....)" is ambiguous 

### ISSUE THREAD

**Issue by sstaszko** [zhoupc/CNMF_E#22]
When I try to run display contours of the neurons, I get the error below. 

Error: File: demo_endoscope.m Line: 202 Column: 40
The construct "Ysignal(...end...)" is ambiguous in this context, because "Ysignal" cannot be ascertained to be either the name of a variable or of a function.  To make it a variable, assign to it; to allow it to become a function at execution time, replace "end" with a call to LENGTH, SIZE, or NUMEL on the desired array.

**Comment by zhoupc** [comment]
did you define a function named 'Ysignal'? usually, Ysignal is just a variable.

**Comment by jaberry** [comment]
When I received this error, it was because the newer version of CNMFE doesn't automatically generate Ysignal. When I tried to run any function that required Ysignal, it would give this error. You have to recreate Ysignal first, and then run the function.

**Comment by sstaszko** [comment]
It is generating Ysignal as a variable and I'm able to run all other functions that call Ysignal.
I took out the portion (:, 1:5:end) from line 202 and it fixed my problem!
