### ISSUE TITLE
Error in updating brackgrand set in demo_large_data_1p.m

### ISSUE THREAD

**Issue by michaelfsp** [zhoupc/CNMF_E#25]
-----------------UPDATE BACKGROUND---------------------------
Error using fit_ring_model (line 39)
Sparse single array arithmetic operations are not supported.

Error in Sources2D/update_background_parallel (line 176)
   parfor mpatch=1:(nr_patch*nc_patch)

Error in demo_large_data_1p (line 139)
neuron.update_background_parallel(use_parallel);

**Comment by zhoupc** [comment]
I added a new push. a similar issue has been reported by others and it's due to sparse representation of neuron.A. i guess the same things happened here. please update the code and check whether new changes fix the issue. 

Best, 
Pengcheng
