### ISSUE TITLE
Error in demo 1p large data, update spatial parallel - zero sparse A column

### ISSUE THREAD

**Issue by in0565** [zhoupc/CNMF_E#38]
Hello,

I'm a graduate student in Prof. Minwhan Jung's lab, KAIST, South Korea.
I have an issue that appears when running `demo_large_data_1p.m`, in the first update of spatial components, after
`[center_res, Cn_res, PNR_res] =neuron.initComponents_residual_parallel([], save_initialization, use_parallel, min_corr_res, min_pnr_res, seed_method_res);`.

The error message leads me to line 66,
` IND = sparse(logical(determine_search_location(obj.A, search_method, options)));`
and again to line 66 of `determine_search_location`, which is a `parfor`.
I run manually this `parfor` and found that in line 69, ` [V,D] = eig(Vr{i});` was stopping me, as a column of obj.A was a zero sparse. I realized that some zero-pixel neurons were existing, but the fixing of this false positives (`remove_false_positives`) is placed after this spatial update in the demo, so I'm opening this issue.

I tried to overcome with starting with higher `min_pnr` and `min_corr` but did not work.

Thanks.
Young Ju.

**Comment by in0565** [comment]
To be specific, (as my Matlab is in Korean) let me describe the error exactly.
It says, "the input matrix should not contain NaN or infinite numbers", which `eig(Vr{i})` makes.
Thanks.

**Comment by zhoupc** [comment]
I fixed the bug by handling this abnormal case. @in0565, can you test the new code and let me know how it works. Thanks.

**Comment by in0565** [comment]
@zhoupc Now it works with no errors. Thanks for your help.
